### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by arcondello** [stevenrhart/max_ind_set#1]
https://github.com/stevenrhart/max_ind_set/blob/c1c914912e399fb586a4fe875c14342f85fc8e8e/max_ind_set_qubo.py#L30
It's generally better practice to use the config file and `dwave setup` command, see [docs](https://docs.ocean.dwavesys.com/en/stable/overview/sapi.html).

https://github.com/stevenrhart/max_ind_set/blob/c1c914912e399fb586a4fe875c14342f85fc8e8e/max_ind_set_qubo.py#L60
It's way more efficient to do 
```
for i in G.nodes:
    Q[(i, i)] = -1
for i, j in G.edges:
    Q[(i, j)] = gamma
```
the reason is imagine that you have a path graph like `[(0, 1), (1, 2), (2, 3)]`, in your case, you're trying all possible edges, while mine just uses the existing ones.

https://github.com/stevenrhart/max_ind_set/blob/c1c914912e399fb586a4fe875c14342f85fc8e8e/max_ind_set_qubo.py#L60
On that note, it ends up working out, but you're checking (and adding) each edge twice, once for `(i, j)` and the other for `(j, i)`. The suggested syntax above would fix that, or you could do
```
for i in range(n):
   for j in range(i, n):
      pass
```

https://github.com/stevenrhart/max_ind_set/blob/c1c914912e399fb586a4fe875c14342f85fc8e8e/max_ind_set_qubo.py#L88
Parameter is `num_reads`, not `num_runs`.

https://github.com/stevenrhart/max_ind_set/blob/c1c914912e399fb586a4fe875c14342f85fc8e8e/max_ind_set_qubo.py#L108
Similar to above, it's better to configure your environment and use the defaults.

**Comment by stevenrhart** [comment]
Thanks for the comments (and code suggestions for for loop). Addressed all feedback and closing.
